server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: admin
    password: test_db1234
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    default-statement-timeout: 30 #DB 응답에 대한 타임아웃
    map-underscore-to-camel-case: true

logging:
  level:
    root: "warn"
    org.springframework.web: "debug"
    org.hibernate: "error"